import woman1 from "../assets/images/woman1.jpg";
import woman2 from "../assets/images/woman2.jpg";
import woman3 from "../assets/images/woman3.jpg";
import woman4 from "../assets/images/woman4.jpg";
import woman5 from "../assets/images/woman5.jpg";
import woman6 from "../assets/images/woman6.jpg";
import man1 from "../assets/images/man1.jpg";
import man2 from "../assets/images/man2.jpg";
import man3 from "../assets/images/man3.jpg";
import man4 from "../assets/images/man4.jpg";
import man5 from "../assets/images/man5.jpg";
import { utilService } from "./util";

const chats = [
  {
    id: "2",
    thumbnail: woman1,
    name: "Love of my life❤️💜",
    phone_number: "+2348123456789",
    whatsapp_name: "Beyonce",
    unread: 3,
    online: true,
    group: false,
    pinned: true,
    typing: false,
    lastMsg: {
      chatId: "2",
      messageType: "txt",
      timeStamp: 1646065058483,
      senderId: "1",
      receiverId: "2",
      content: utilService.getRandomSentence(),
    },
  },
  {
    id: "1",
    thumbnail: woman2,
    name: "Karen Okonkwo",
    phone_number: "+2348123456789",
    whatsapp_name: "karen",
    unread: 1,
    online: false,
    group: false,
    pinned: false,
    typing: true,
    lastMsg: {
      chatId: "1",
      messageType: "txt",
      timeStamp: 1646065058483,
      senderId: "1",
      receiverId: "1",
      content: utilService.getRandomSentence(),
    },
  },

  {
    id: "3",
    thumbnail: man1,
    name: "bob  from the office",
    phone_number: "+2348123456789",
    whatsapp_name: "bobi",
    unread: 0,
    online: false,
    group: false,
    pinned: false,
    typing: false,
    lastMsg: {
      chatId: "3",
      messageType: "txt",
      timeStamp: 1646065058483,
      senderId: "3",
      receiverId: "1",
      content: utilService.getRandomSentence(),
    },
  },
  {
    id: "4",
    thumbnail: woman3,
    name: "Maia lee",
    phone_number: "+2348123456789",
    whatsapp_name: "Mayush",
    unread: 1,
    online: true,
    group: false,
    pinned: false,
    typing: true,
    lastMsg: {
      chatId: "4",
      messageType: "txt",
      timeStamp: 1646065056483,
      senderId: "4",
      receiverId: "1",
      content: utilService.getRandomSentence(),
    },
  },
  {
    id: "5",
    thumbnail: man2,
    name: "Josh",
    phone_number: "+2348123456789",
    whatsapp_name: "Josh",
    unread: 6,
    online: true,
    group: false,
    pinned: false,
    typing: false,
    lastMsg: {
      chatId: "5",
      messageType: "txt",
      timeStamp: 1646065045483,
      senderId: "1 ",
      receiverId: "5",
      content: utilService.getRandomSentence(),
    },
  },
  {
    id: "6",
    thumbnail: man3,
    name: "Justin Bieber",
    phone_number: "+2348123456789",
    whatsapp_name: "my bea",
    unread: 0,
    online: false,
    group: false,
    pinned: false,
    typing: false,
    lastMsg: {
      chatId: "6",
      messageType: "txt",
      timeStamp: 1646065052483,
      senderId: "6",
      receiverId: "1",
      content: utilService.getRandomSentence(),
    },
  },
  {
    id: "7",
    thumbnail: woman4,
    name: "Rachel Green",
    phone_number: "+2348123456789",
    whatsapp_name: "rachel green",
    unread: 5,
    online: false,
    group: false,
    pinned: false,
    typing: true,
    lastMsg: {
      chatId: "7",
      messageType: "txt",
      timeStamp: 1646065058483,
      senderId: "7",
      receiverId: "1",
      content: utilService.getRandomSentence(),
    },
  },
  {
    id: "8",
    thumbnail: woman5,
    name: "Lily Aldrin",
    phone_number: "+2348123456789",
    whatsapp_name: "lily",
    unread: 0,
    online: false,
    group: false,
    pinned: false,
    typing: false,
    lastMsg: {
      chatId: "8",
      messageType: "txt",
      timeStamp: 1646055058483,
      senderId: "1",
      receiverId: "8",
      content: utilService.getRandomSentence(),
    },
  },
  {
    id: "9",
    thumbnail: man4,
    name: "Josh",
    phone_number: "+2348123456789",
    whatsapp_name: "Josh",
    unread: 0,
    online: false,
    group: false,
    pinned: false,
    typing: false,
    lastMsg: {
      chatId: "9",
      messageType: "txt",
      timeStamp: 1646065058483,
      senderId: "9",
      receiverId: "1",
      content: utilService.getRandomSentence(),
    },
  },
  {
    id: "10",
    thumbnail: woman6,
    name: "Mom",
    phone_number: "+2348123456789",
    whatsapp_name: "Irit",
    unread: 1,
    online: false,
    group: false,
    pinned: false,
    typing: true,
    lastMsg: {
      chatId: "10",
      messageType: "txt",
      timeStamp: 1646065058483,
      senderId: "1",
      receiverId: "10",
      content: utilService.getRandomSentence(),
    },
  },
  {
    id: "11",
    thumbnail: man5,
    name: "Jake Puck",
    phone_number: "+2348123456789",
    whatsapp_name: "jake",
    unread: 0,
    online: false,
    group: false,
    pinned: false,
    typing: false,
    lastMsg: {
      chatId: "11",
      messageType: "txt",
      timeStamp: 1646065058483,
      senderId: "11",
      receiverId: "1",
      content: utilService.getRandomSentence(),
    },
  },
];

const msgs = [
  {
    id: "1",
    chatId: "1",
    messageType: "txt",
    timeStamp: 1646027523326,
    senderId: "1",
    receiverId: "2",
    content: utilService.getRandomSentence(),
  },
  {
    id: "2",
    chatId: "1",
    messageType: "txt",
    timeStamp: 1646028523326,
    senderId: "1",
    receiverId: "2",
    content: utilService.getRandomSentence(),
  },
  {
    id: "3",
    chatId: "1",
    messageType: "txt",
    timeStamp: 1646038523226,
    senderId: "2",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "4",
    chatId: "1",
    messageType: "txt",
    timeStamp: 1646038523216,
    senderId: "1",
    receiverId: "2",
    content: utilService.getRandomSentence(),
  },
  {
    id: "5",
    chatId: "1",
    messageType: "txt",
    timeStamp: 1646038523326,
    senderId: "2",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "6",
    chatId: "1",
    messageType: "txt",
    timeStamp: 1646038523326,
    senderId: "1",
    receiverId: "2",
    content: utilService.getRandomSentence(),
  },
  {
    id: "7",
    chatId: "1",
    messageType: "txt",
    timeStamp: 1646038523326,
    senderId: "1",
    receiverId: "2",
    content: utilService.getRandomSentence(),
  },
  {
    id: "8",
    chatId: "1",
    messageType: "txt",
    timeStamp: 1646038523326,
    senderId: "1",
    receiverId: "2",
    content: utilService.getRandomSentence(),
  },
  {
    id: "9",
    chatId: "1",
    messageType: "txt",
    timeStamp: 1646038523326,
    senderId: "1",
    receiverId: "2",
    content: utilService.getRandomSentence(),
  },
  {
    id: "10",
    chatId: "1",
    messageType: "txt",
    timeStamp: 1646038523326,
    senderId: "1",
    receiverId: "2",
    content: utilService.getRandomSentence(),
  },
  {
    id: "11",
    chatId: "2",
    messageType: "txt",
    timeStamp: 1645008523326,
    senderId: "3",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "12",
    chatId: "2",
    messageType: "txt",
    timeStamp: 1645038523326,
    senderId: "3",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "13",
    chatId: "2",
    messageType: "txt",
    timeStamp: 1645078523326,
    senderId: "3",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "14",
    chatId: "2",
    messageType: "txt",
    timeStamp: 1645038222226,
    senderId: "1",
    receiverId: "3",
    content: utilService.getRandomSentence(),
  },
  {
    id: "15",
    chatId: "2",
    messageType: "txt",
    timeStamp: 1646038220026,
    senderId: "3",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "16",
    chatId: "3",
    messageType: "txt",
    timeStamp: 1646038523326,
    senderId: "4",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "17",
    chatId: "3",
    messageType: "txt",
    timeStamp: 1646038523326,
    senderId: "4",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "18",
    chatId: "3",
    messageType: "txt",
    timeStamp: 1646038523326,
    senderId: "1",
    receiverId: "4",
    content: utilService.getRandomSentence(),
  },
  {
    id: "19",
    chatId: "3",
    messageType: "txt",
    timeStamp: 1646038523326,
    senderId: "4",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "20",
    chatId: "3",
    messageType: "txt",
    timeStamp: 1646038523326,
    senderId: "1",
    receiverId: "4",
    content: utilService.getRandomSentence(),
  },
  {
    id: "21",
    chatId: "3",
    messageType: "txt",
    timeStamp: 1646038523326,
    senderId: "4",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "22",
    chatId: "3",
    messageType: "txt",
    timeStamp: 1646038523326,
    senderId: "1",
    receiverId: "4",
    content: utilService.getRandomSentence(),
  },
  {
    id: "23",
    chatId: "3",
    messageType: "txt",
    timeStamp: 1646038523326,
    senderId: "1",
    receiverId: "4",
    content: utilService.getRandomSentence(),
  },
  {
    id: "24",
    chatId: "4",
    messageType: "txt",
    timeStamp: 1646038523326,
    senderId: "5",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "25",
    chatId: "4",
    messageType: "txt",
    timeStamp: 1646038523326,
    senderId: "1",
    receiverId: "5",
    content: utilService.getRandomSentence(),
  },
  {
    id: "26",
    chatId: "4",
    messageType: "txt",
    timeStamp: 1646038523326,
    senderId: "5",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "27",
    chatId: "4",
    messageType: "txt",
    timeStamp: 1646038523326,
    senderId: "1",
    receiverId: "5",
    content: utilService.getRandomSentence(),
  },
  {
    id: "28",
    chatId: "4",
    messageType: "txt",
    timeStamp: 1646038523326,
    senderId: "5",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "29",
    chatId: "4",
    messageType: "txt",
    timeStamp: 1646038523326,
    senderId: "1",
    receiverId: "5",
    content: utilService.getRandomSentence(),
  },
  {
    id: "30",
    chatId: "4",
    messageType: "img",
    timeStamp: 1646038523326,
    senderId: "1",
    receiverId: "5",
    content:
      "https://res.cloudinary.com/nofar/image/upload/v1622110851/qvgxvymdcubaefgbdobq.jpg",
  },
  {
    id: "30",
    chatId: "5",
    messageType: "txt",
    timeStamp: 1646038423326,
    senderId: "1",
    receiverId: "5",
    content: utilService.getRandomSentence(),
  },
  {
    id: "31",
    chatId: "5",
    messageType: "txt",
    timeStamp: 1646038423026,
    senderId: "5",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },

  {
    id: "32",
    chatId: "5",
    messageType: "txt",
    timeStamp: 1646038423006,
    senderId: "1",
    receiverId: "5",
    content: utilService.getRandomSentence(),
  },
  {
    id: "33",
    chatId: "5",
    messageType: "txt",
    timeStamp: 1646038413326,
    senderId: "1",
    receiverId: "5",
    content: utilService.getRandomSentence(),
  },
  {
    id: "34",
    chatId: "5",
    messageType: "txt",
    timeStamp: 1646038413026,
    senderId: "5",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "35",
    chatId: "5",
    messageType: "txt",
    timeStamp: 1646038412006,
    senderId: "1",
    receiverId: "5",
    content: utilService.getRandomSentence(),
  },
  {
    id: "36",
    chatId: "5",
    messageType: "img",
    timeStamp: 1646038423026,
    senderId: "5",
    receiverId: "1",
    content:
      "https://res.cloudinary.com/nofar/image/upload/v1611307118/bwsrqk1kzouonqi3p6k6.webp",
  },
  {
    id: "37",
    chatId: "5",
    messageType: "img",
    timeStamp: 1646145224035,
    senderId: "1",
    receiverId: "2",
    content:
      "https://res.cloudinary.com/nofar/image/upload/v1611491376/z2s7hcyoxn2malft72dd.jpg",
  },
  {
    id: "38",
    chatId: "3",
    messageType: "img",
    timeStamp: 1646145224035,
    senderId: "3",
    receiverId: "1",
    content:
      "https://res.cloudinary.com/nofar/image/upload/v1612127155/rgnx5rsklkozfuejwjsg.jpg",
  },
  {
    id: "39",
    chatId: "3",
    messageType: "txt",
    timeStamp: 1646145332357,
    senderId: "1",
    receiverId: "3",
    content: utilService.getRandomSentence(),
  },
  {
    id: "40",
    chatId: "3",
    messageType: "txt",
    timeStamp: 1646145333357,
    senderId: "3",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "41",
    chatId: "6",
    messageType: "txt",
    timeStamp: 1646145333357,
    senderId: "6",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "42",
    chatId: "6",
    messageType: "txt",
    timeStamp: 1646145334357,
    senderId: "6",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "43",
    chatId: "6",
    messageType: "txt",
    timeStamp: 1646145334457,
    senderId: "1",
    receiverId: "6",
    content: utilService.getRandomSentence(),
  },
  {
    id: "44",
    chatId: "6",
    messageType: "txt",
    timeStamp: 1646145333357,
    senderId: "6",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "45",
    chatId: "6",
    messageType: "txt",
    timeStamp: 1646145333357,
    senderId: "6",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "46",
    chatId: "6",
    messageType: "txt",
    timeStamp: 1646145333557,
    senderId: "6",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "47",
    chatId: "6",
    messageType: "img",
    timeStamp: 1646145224035,
    senderId: "1",
    receiverId: "6",
    content:
      "https://res.cloudinary.com/nofar/image/upload/v1614948332/photo-1515562141207-7a88fb7ce338_xysfhr.jpg",
  },
  {
    id: "48",
    chatId: "7",
    messageType: "txt",
    timeStamp: 1646145335557,
    senderId: "1",
    receiverId: "7",
    content: utilService.getRandomSentence(),
  },
  {
    id: "49",
    chatId: "7",
    messageType: "txt",
    timeStamp: 1646145335577,
    senderId: "1",
    receiverId: "7",
    content: utilService.getRandomSentence(),
  },
  {
    id: "50",
    chatId: "7",
    messageType: "txt",
    timeStamp: 1646145333357,
    senderId: "7",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "51",
    chatId: "7",
    messageType: "txt",
    timeStamp: 1646145334357,
    senderId: "7",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "52",
    chatId: "7",
    messageType: "txt",
    timeStamp: 1646145334457,
    senderId: "1",
    receiverId: "7",
    content: utilService.getRandomSentence(),
  },
  {
    id: "53",
    chatId: "7",
    messageType: "txt",
    timeStamp: 1646145333357,
    senderId: "7",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "54",
    chatId: "7",
    messageType: "txt",
    timeStamp: 1646145333357,
    senderId: "7",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "55",
    chatId: "7",
    messageType: "txt",
    timeStamp: 1646145333557,
    senderId: "7",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "56",
    chatId: "7",
    messageType: "img",
    timeStamp: 1646145224035,
    senderId: "1",
    receiverId: "7",
    content:
      "https://res.cloudinary.com/nofar/image/upload/v1614948332/photo-1515562141207-7a88fb7ce338_xysfhr.jpg",
  },
  {
    id: "57",
    chatId: "7",
    messageType: "txt",
    timeStamp: 1646145335557,
    senderId: "1",
    receiverId: "7",
    content: utilService.getRandomSentence(),
  },
  {
    id: "58",
    chatId: "7",
    messageType: "txt",
    timeStamp: 1646145335577,
    senderId: "1",
    receiverId: "7",
    content: utilService.getRandomSentence(),
  },
  {
    id: "59",
    chatId: "7",
    messageType: "txt",
    timeStamp: 1646145335557,
    senderId: "1",
    receiverId: "7",
    content: utilService.getRandomSentence(),
  },
  {
    id: "60",
    chatId: "7",
    messageType: "txt",
    timeStamp: 1646145335577,
    senderId: "7",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "61",
    chatId: "7",
    messageType: "txt",
    timeStamp: 1646145335557,
    senderId: "7",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "62",
    chatId: "7",
    messageType: "txt",
    timeStamp: 1646145335577,
    senderId: "1",
    receiverId: "7",
    content: utilService.getRandomSentence(),
  },
  {
    id: "63",
    chatId: "8",
    messageType: "txt",
    timeStamp: 1646145335557,
    senderId: "1",
    receiverId: "8",
    content: utilService.getRandomSentence(),
  },
  {
    id: "64",
    chatId: "8",
    messageType: "txt",
    timeStamp: 1646145335577,
    senderId: "1",
    receiverId: "8",
    content: utilService.getRandomSentence(),
  },
  {
    id: "65",
    chatId: "8",
    messageType: "txt",
    timeStamp: 1646145333357,
    senderId: "8",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "66",
    chatId: "8",
    messageType: "txt",
    timeStamp: 1646145334357,
    senderId: "8",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "67",
    chatId: "8",
    messageType: "txt",
    timeStamp: 1646145334457,
    senderId: "1",
    receiverId: "8",
    content: utilService.getRandomSentence(),
  },
  {
    id: "68",
    chatId: "8",
    messageType: "txt",
    timeStamp: 1646145333357,
    senderId: "8",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "69",
    chatId: "8",
    messageType: "txt",
    timeStamp: 1646145333357,
    senderId: "8",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "70",
    chatId: "8",
    messageType: "txt",
    timeStamp: 1646145333557,
    senderId: "8",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "71",
    chatId: "8",
    messageType: "img",
    timeStamp: 1646145224035,
    senderId: "1",
    receiverId: "8",
    content:
      "https://res.cloudinary.com/nofar/image/upload/v1610698514/pfliraj279bjswoureny.jpg",
  },
  {
    id: "72",
    chatId: "8",
    messageType: "txt",
    timeStamp: 1646145335557,
    senderId: "1",
    receiverId: "8",
    content: utilService.getRandomSentence(),
  },
  {
    id: "73",
    chatId: "8",
    messageType: "txt",
    timeStamp: 1646145335577,
    senderId: "1",
    receiverId: "8",
    content: utilService.getRandomSentence(),
  },
  {
    id: "74",
    chatId: "8",
    messageType: "txt",
    timeStamp: 1646145335557,
    senderId: "1",
    receiverId: "8",
    content: utilService.getRandomSentence(),
  },
  {
    id: "75",
    chatId: "8",
    messageType: "txt",
    timeStamp: 1646145335577,
    senderId: "8",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "76",
    chatId: "8",
    messageType: "txt",
    timeStamp: 1646145335557,
    senderId: "8",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "77",
    chatId: "8",
    messageType: "txt",
    timeStamp: 1646145335577,
    senderId: "1",
    receiverId: "8",
    content: utilService.getRandomSentence(),
  },
  {
    id: "78",
    chatId: "9",
    messageType: "txt",
    timeStamp: 1646145335557,
    senderId: "1",
    receiverId: "9",
    content: utilService.getRandomSentence(),
  },
  {
    id: "79",
    chatId: "9",
    messageType: "txt",
    timeStamp: 1646145335577,
    senderId: "1",
    receiverId: "9",
    content: utilService.getRandomSentence(),
  },
  {
    id: "80",
    chatId: "9",
    messageType: "txt",
    timeStamp: 1646145335557,
    senderId: "1",
    receiverId: "9",
    content: utilService.getRandomSentence(),
  },
  {
    id: "81",
    chatId: "9",
    messageType: "txt",
    timeStamp: 1646145335577,
    senderId: "9",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "82",
    chatId: "9",
    messageType: "txt",
    timeStamp: 1646145335557,
    senderId: "9",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "83",
    chatId: "9",
    messageType: "txt",
    timeStamp: 1646145335577,
    senderId: "1",
    receiverId: "9",
    content: utilService.getRandomSentence(),
  },
  {
    id: "84",
    chatId: "10",
    messageType: "txt",
    timeStamp: 1646145335557,
    senderId: "1",
    receiverId: "10",
    content: utilService.getRandomSentence(),
  },
  {
    id: "85",
    chatId: "10",
    messageType: "txt",
    timeStamp: 1646145335577,
    senderId: "1",
    receiverId: "10",
    content: utilService.getRandomSentence(),
  },
  {
    id: "86",
    chatId: "10",
    messageType: "txt",
    timeStamp: 1646145335557,
    senderId: "1",
    receiverId: "10",
    content: utilService.getRandomSentence(),
  },
  {
    id: "87",
    chatId: "10",
    messageType: "txt",
    timeStamp: 1646145335577,
    senderId: "10",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "88",
    chatId: "10",
    messageType: "txt",
    timeStamp: 1646145335557,
    senderId: "10",
    receiverId: "1",
    content: utilService.getRandomSentence(),
  },
  {
    id: "89",
    chatId: "10",
    messageType: "txt",
    timeStamp: 1646145335577,
    senderId: "1",
    receiverId: "10",
    content: utilService.getRandomSentence(),
  },
];

export const data = {
  chats,
  msgs,
};
